import "./globals.css";
import Sidebar from "@/components/SideBar";
export const metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex h-screen bg-bgMain overflow-hidden">

            <div className="bg-bgSidebar shrink-0">
                <Sidebar />
            </div>

            
            <div className="flex-1 overflow-y-auto min-w-0 bg-bgMain">
                {children}
            </div>

        </div>

        
      </body>
    </html>
  );
}
